[build]
  command = "CI=false ESLINT_NO_DEV_ERRORS=true TSC_COMPILE_ON_ERROR=true npm run build"
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  functionsPort = 8888

# Set environment variables for Firebase
[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--legacy-peer-deps --no-fund --no-audit"
  CI = "false"
  NODE_ENV = "production"
  TSC_COMPILE_ON_ERROR = "true"
  ESLINT_NO_DEV_ERRORS = "true"

[template.environment]
  REACT_APP_SITE_URL = "YOUR_NETLIFY_SITE_URL"
  CLOUDINARY_CLOUD_NAME = "di1nyp1bb"
  CLOUDINARY_API_KEY = "797786557437997"
  CLOUDINARY_API_SECRET = "OERwE_u2Cik88JtQk57eLSiLfos"
  REACT_APP_FIREBASE_API_KEY = "AIzaSyBOD92Z4Td2T0pJS-2FFqWqHGFdp2Y6OVo"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "alchies-web.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "alchies-web"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "alchies-web.firebasestorage.app"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "331540359179"
  REACT_APP_FIREBASE_APP_ID = "1:331540359179:web:b41dfb174c0abac5c97f0e"
  REACT_APP_FIREBASE_MEASUREMENT_ID = "G-TSJG8FV1HN" 