[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  functionsPort = 8888

[template.environment]
  REACT_APP_SITE_URL = "YOUR_NETLIFY_SITE_URL"
  CLOUDINARY_CLOUD_NAME = "di1nyp1bb"
  CLOUDINARY_API_KEY = "797786557437997"
  CLOUDINARY_API_SECRET = "OERwE_u2Cik88JtQk57eLSiLfos" 